name: Build and Release MCP Installer

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            script_file: install.sh
            artifact_name: plantos-mcp-installer-macos.command
            asset_name: plantos-mcp-installer-macos.command
          - os: windows-latest
            script_file: install.bat
            artifact_name: plantos-mcp-installer-windows.bat
            asset_name: plantos-mcp-installer-windows.bat
          - os: ubuntu-latest
            script_file: install.sh
            artifact_name: plantos-mcp-installer-linux.sh
            asset_name: plantos-mcp-installer-linux.sh

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Package installer (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          mkdir -p dist
          # Copy as .command for double-click support
          cp install.sh "dist/Install Plantos MCP.command"
          chmod +x "dist/Install Plantos MCP.command"

          # Also include plain .sh for advanced users
          cp install.sh "dist/install-plantos-mcp.sh"
          chmod +x "dist/install-plantos-mcp.sh"

          # Create zip with both files
          cd dist
          zip -r plantos-mcp-installer-macos.zip "Install Plantos MCP.command" "install-plantos-mcp.sh"

      - name: Package installer (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path dist
          # Copy batch file with user-friendly name
          Copy-Item install.bat "dist\Install Plantos MCP.bat"

          # Create zip
          Compress-Archive -Path "dist\Install Plantos MCP.bat" -DestinationPath "dist\plantos-mcp-installer-windows.zip"

      - name: Package installer (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir -p dist
          # Copy shell script
          cp install.sh "dist/install-plantos-mcp.sh"
          chmod +x "dist/install-plantos-mcp.sh"

          # Create tarball
          cd dist
          tar -czf plantos-mcp-installer-linux.tar.gz install-plantos-mcp.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: dist/${{ matrix.os == 'macos-latest' && 'plantos-mcp-installer-macos.zip' || matrix.os == 'windows-latest' && 'plantos-mcp-installer-windows.zip' || 'plantos-mcp-installer-linux.tar.gz' }}

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -R artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/plantos-mcp-installer-macos.command/plantos-mcp-installer-macos.zip
            artifacts/plantos-mcp-installer-windows.bat/plantos-mcp-installer-windows.zip
            artifacts/plantos-mcp-installer-linux.sh/plantos-mcp-installer-linux.tar.gz
          draft: false
          prerelease: false
          generate_release_notes: true
          body: |
            ## Plantos MCP Installer

            Simple one-click installer to connect Plantos agricultural intelligence to Claude Desktop.

            ### Installation

            **macOS:**
            1. Download `plantos-mcp-installer-macos.zip`
            2. Unzip the file
            3. **Double-click** `Install Plantos MCP.command`
            4. Follow the on-screen instructions
            5. Restart Claude Desktop when complete

            **Windows:**
            1. Download `plantos-mcp-installer-windows.zip`
            2. Extract the file
            3. **Double-click** `Install Plantos MCP.bat`
            4. Follow the on-screen instructions
            5. Restart Claude Desktop when complete

            **Linux:**
            1. Download `plantos-mcp-installer-linux.tar.gz`
            2. Extract: `tar -xzf plantos-mcp-installer-linux.tar.gz`
            3. Run: `./install-plantos-mcp.sh`
            4. Follow the on-screen instructions
            5. Restart Claude Desktop when complete

            ### How It Works

            The installer will:
            1. Check for Python 3 (required for MCP servers)
            2. Open your browser to authorize the connection
            3. Install the Plantos MCP package
            4. Automatically configure Claude Desktop
            5. You're ready to go!

            ### What's Included

            - 🌾 Agricultural data analysis tools
            - 📊 Crop yield predictions
            - 🌱 Soil health insights
            - 🌤️ Weather data integration
            - 📈 Market intelligence

            ### Requirements

            - Python 3.10 or later
            - Claude Desktop
            - Plantos Pro subscription (installer will guide you through signup)

            For more information, visit [plantos.co](https://plantos.co)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
